### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by braaar** [braaar/jam-assistant#20]
**Features we want in the future**
- [x] Key center and key mode selection (e.g. "G" and "minor", "F" and "mixolydian", etc.)
- [ ] Providing chord progressions instead of just random chords (see #14) 
- [ ] Time signature selection/randomization
- [x] Display chords in a chord chart ([see example](https://i.imgur.com/dK3Y09a.png))
- [ ] Different chord lengths 
- [ ] Special challenge cards (see #1)
- [ ] Rarity system for weighted randomness (Common, Uncommon, Rare, Epic, Legendary) 

Loose discussion about future ideas is welcome in this issue, but feel free to create issues for more specialised discussion of specific features.
